# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='full_path',
        ),
    ]
