# Generated by Django 2.0 on 2018-03-03 15:33

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_auto_20180303_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Risk category name')),
                ('description', models.TextField(max_length=700, verbose_name='Description')),
                ('example', models.TextField(max_length=700, verbose_name='Example')),
                ('slug', models.SlugField(unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riskcategories', to='risk.Risk', verbose_name='parent category')),
            ],
            options={
                'verbose_name_plural': 'Risks',
            },
        ),
    ]
