# Generated by Django 2.0 on 2018-03-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
