# Generated by Django 2.0 on 2018-03-03 19:58

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import risk.models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0009_auto_20180303_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsesCategory', models.CharField(choices=[('ACC', 'Accept'), ('MIT', 'Mitigate'), ('INS', 'Insure'), ('HED', 'Hedge')], default='ACC', max_length=3, verbose_name='Responses category')),
                ('description', models.TextField(default='Detailed description', max_length=300, verbose_name='Description')),
                ('draftingdate', models.DateField(blank=True, default=risk.models.my_date, null=True, verbose_name='Drafting date')),
                ('deadlineDate', models.DateField(blank=True, default=risk.models.my_date, null=True, verbose_name='Deadline date')),
                ('risk', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk.Risk')),
            ],
            options={
                'verbose_name_plural': 'Responses',
            },
        ),
    ]
